### ISSUE TITLE
Name Input Validation for middle-names

### ISSUE THREAD

**Issue by SamimNaser** [ankitsm08/id-card-maker#1]
The website has no option for middle-name so the people with first-name middle-name and surname so people can not give their full name as input.
e.g. [Zayne] [Jaycob] [Derek]
The System has option to either give input as  [Zayne] [Derek] or  [Zayne] [Jaycob]

**Comment by ankitsm08** [comment]
Support for middle-name is now implemented. Thanks for noticing that, since it didnt cross my mind.
commit: [2c652737fd9d001cc2e06a40e5c756bcbeb64921](https://github.com/ankitsm08/id-card-maker/commit/2c652737fd9d001cc2e06a40e5c756bcbeb64921)

Now the input field allows for names as first-last and also as first-middle-last.
